### ISSUE TITLE
sed errors

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/google-deployment-manager-neo4j#6]
Check the logs.  I see stuff like this.

Mar 25 11:11:30 customds2-cluster-instance-cb5c google_metadata_script_runner[1717]: startup-script: sed: -e expression #1, char 3: expected \ after `a', `c' or `i'

**Comment by drumcircle** [comment]
On it

**Comment by drumcircle** [comment]
Ben, please do a pull.  I mistakenly pushed to main the error around 1.00 yesterday.  It was fixed by 3.00pm - apologies.

I pulled the active neo4j.conf file on your Ben11 image.  It does not have the last line, which is from the SED error.

dbms.security.procedures.allowlist=apoc.*,gds.*,bloom.*
<nothing here>

The last line, which appears on mine, looks like this:
dbms.security.procedures.allowlist=apoc.*,gds.*,bloom.*

**Comment by benofben** [comment]
Hrmmmm, still seeing this.  Though, Bloom and GDS are coming up.  Using the keys from the lab here: https://github.com/neo4j-partners/hands-on-lab-neo4j-and-vertex-ai/tree/main/Lab%201%20-%20Deploy%20Neo4j

Mar 28 07:07:55 neo4j-cluster-instance-tskd google_metadata_script_runner[1747]: startup-script: sed: -e expression #1, char 3: expected \ after `a', `c' or `i'
Mar 28 07:07:55 neo4j-cluster-instance-tskd google_metadata_script_runner[1747]: startup-script: Writing Bloom license key file...
Mar 28 07:07:55 neo4j-cluster-instance-tskd google_metadata_script_runner[1747]: startup-script: Configuring Bloom license in neo4j.conf...
Mar 28 07:07:55 neo4j-cluster-instance-tskd google_metadata_script_runner[1747]: startup-script: Writing GDS license key file...
Mar 28 07:07:55 neo4j-cluster-instance-tskd google_metadata_script_runner[1747]: startup-script: Configuring GDS license in neo4j.conf...
Mar 28 07:07:55 neo4j-cluster-instance-tskd google_metadata_script_runner[1747]: startup-script: sed: -e expression #1, char 3: expected \ after `a', `c' or `i'

**Comment by drumcircle** [comment]
Removed offending blank line generator
